apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: hello-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/hello-dev/hello